### ISSUE TITLE
framexs.skelton

### ISSUE THREAD

**Issue by AirQuick** [nandaka-furari/framexs#1]
もしかして、本来 skel**e**ton なのでは…?

**Comment by nandaka-furari** [comment]
その通りですね。スペルミスです。
ご指摘ありがとうございます。

**Comment by nandaka-furari** [comment]
ところでツイッターアカウントは持っていますか？

**Comment by AirQuick** [comment]
SNS はやっていないので、一連の issues についても、

1. 何か全く別件を探している過程で、このレポジトリを開いた。
1. めずらしいので、なんとなくコードを見た。
1. `<?framexs.addpath?>` が不要そうに見えた。→ #2 誕生
1. #2 を試すとき、IDE に `$skeleton_loc` といれたら、「そんな変数ない」といわれた。→ #1 誕生
1. #2 を試すために `addpath` でコードを検索したら、`@framexs:addpath` も不要そうに見えた。→ #3 誕生

という、まあ、流れです…

**Comment by nandaka-furari** [comment]
なるほど。
せっかくできた縁ですので今後も何かやり取りができると思いますね。

**Comment by nandaka-furari** [comment]
問題は解決したので閉じます。
