### ISSUE TITLE
<?framexs.addpath?>

### ISSUE THREAD

**Issue by AirQuick** [nandaka-furari/framexs#2]
https://github.com/nandaka-furari/framexs/blob/d475b3e45f86b47fae911ab0af715fc607c54c5b/framexs.xsl#L12 を
```xml
	<xsl:param name="framexs.addpath" select="concat($skelton_loc, '/../')"/>
```
とかにすれば不要なのでは…?

**Comment by nandaka-furari** [comment]
/uta.xhtml
と
/dir1/uta.xhtml
と
/dir1/dir2/uta.xhtml
の3つのコンテンツから
/template_a.xhtml
をテンプレートにしたときにどうなるかを考える必要があります。
/
template_a.xhtmlの中で
```
<a href="template_a.xhtml">template_a.xhtml</a>
```
というコードがあったとしたら各コンテンツでaddpathコマンドによる適切な指定をしないとリンクが正しくなくなります。
しかし適切な指定をした場合は

|ファイル|パス|
|---|---|
|/uta.xhtml|template_a.xhtml|
|/dir1/uta.xhtml|../template_a.xhtml|
|/dir1/dir2/uta.xhtml|../../template_a.xhtml|

とすることができます。
詳しくはリポジトリの中の/example/pathディレクトリ以下にあるファイルを参考にしてください。
このファイルが適切なリンクになるためにはXSLのconcatだけでは解決できないことが分かります。

**Comment by AirQuick** [comment]
提案を実際に試しました？

**Comment by nandaka-furari** [comment]
失礼。答えたときは試していませんでした。
今試してみましたが動いているようです。これで行けそうです。
ご指摘ありがとうございます。
